### ISSUE TITLE
Receiving Invocation with requestId [] failed: org.apache.commons.logging.LogFactoryjava.lang.NoClassDefFoundError: org.apache.commons.logging.LogFactory for serverless function build with micronaut-bom 1.2.10 , graal 19.2.1 and aws sdk 2.10.56

### ISSUE THREAD

**Issue by ShubhadaRaut** [micronaut-projects/micronaut-aws#187]
Created an application  using micronaut bom 1.2.10 version, along with  software.amazon.awssdk:lambda:2.10.56 & software.amazon.awssdk:s3:2.10.56 dependencies which had functionality to retrieve data from s3 storage and used graal 19.2.1 to create a native image.
The native image is successfully created but when i try to access the endpoint it fails for below exception:
`failed: org.apache.commons.logging.LogFactoryjava.lang.NoClassDefFoundError: org.apache.commons.logging.LogFactory `
and series of exceptions with specifically while creating S3 client.
The exception also had failure at below point:
`failed: Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactoryjava.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory`
******************************
Code for S3Client :
`S3Client s3Client = S3Client.builder().region(getRegion()).build();`

***********
build-native-image.sh

${GRAALVM_HOME}/bin/native-image --no-server -cp example-function-*-all.jar \
              -H:IncludeResources="git.properties" \
              -H:IncludeResources="logback.xml" \
              -H:IncludeResources="application.properties" \

**Comment by RoadRunner120485** [comment]
I had the same problem and found that solution at quarkus: https://github.com/quarkusio/quarkus/issues/4528

This worked for me. 

Maybe one could replace `org.jboss.logging:commons-logging-jboss-logging` with `log4j-over-slf4j` bridge.

**Comment by alvarosanchez** [comment]
The `commons-logging` dependency is brought transitively by `com.amazonaws:aws-java-sdk-core`.

@RoadRunner120485 what is the replacement that you used?

**Comment by RoadRunner120485** [comment]
in my `build.gradle.kts` I'm excluding `commons-logging` explicitly for all projects:
```
allprojects {
    configurations {
        all {
            exclude(group = "commons-logging")
        }
    }
}
```

and in the module where I use aws SDK v2, I explicitly include `org.jboss.logging:commons-logging-jboss-logging`:
```
dependencies {
  implementation("org.jboss.logging:commons-logging-jboss-logging:1.0.0.Final")
}
```

**Comment by alvarosanchez** [comment]
Right, I think `org.slf4j:jcl-over-slf4j` is a better replacement

**Comment by RoadRunner120485** [comment]
👍 I agree. It was just the first solution that I found and it worked. So I left it at that. 

But `jcl-over-slf4j` was what I meant when I wrote `log4j-over-slf4j`just copy & wasted the wrong name ... I mean things that contain `jboss` in it's name could not be the best solution for anything 😄

**Comment by ShubhadaRaut** [comment]
Thank you, Sorry for the delay in reply. I used jcl-over-slf4j and the error is gone . thanks once again
