### ISSUE TITLE
Error while Initializing AWS Lambda

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-aws#1568]
### Expected Behavior

Requests to flow through

### Actual Behaviour

Exception:

```
Suppressed: java.lang.Exception: #block terminated with an error
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
at reactor.core.publisher.Flux.blockFirst(Flux.java:2701)
at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:499)
at io.micronaut.http.client.BlockingHttpClient.exchange(BlockingHttpClient.java:77)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:358)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:146)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:50)
Caused by: java.lang.ClassCastException: java.util.TreeMap cannot be cast to com.amazonaws.serverless.proxy.model.SingleValueHeaders
at <redacted>.$com_amazonaws_serverless_proxy_model_AwsProxyRequest$Introspection.dispatchOne(Unknown Source)
at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanPropertyImpl.setUnsafe(AbstractInitializableBeanIntrospection.java:453)
at io.micronaut.serde.support.deserializers.DeserBean$DerProperty.set(DeserBean.java:714)
at io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.readProperties(SimpleObjectDeserializer.java:101)
at io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.deserialize(SimpleObjectDeserializer.java:59)
at io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:131)
at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:116)
at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:167)
at io.micronaut.json.codec.MapperMediaTypeCodec.decode(MapperMediaTypeCodec.java:190)
at io.micronaut.http.client.netty.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:279)
at io.micronaut.http.client.netty.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:217)
at java.util.HashMap.computeIfAbsent(HashMap.java:1134)
at io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:191)
at io.micronaut.http.client.netty.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:110)
at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:2186)
```

### Steps To Reproduce

App using `micronaut-aws-api-proxy`

I've tried this with both Micronaut AWS 3.10.x and 3.11.x

### Environment Information

- Operating System: MacOS
- Java Version: 11
- GraalVM 22.3.0

### Example Application

N/A

### Version

3.8.0

**Comment by driverpt** [comment]
Extra Context:

Added

```
@Introspected(classes = {
    AlbContext.class,
    ApiGatewayAuthorizerContext.class,
    ApiGatewayRequestIdentity.class,
    AwsProxyRequest.class,
    AwsProxyRequestContext.class,
    AwsProxyResponse.class,
    CognitoAuthorizerClaims.class,
    SingleValueHeaders.class,
    TreeMap.class,
    ContainerConfig.class,
    ErrorModel.class,
    Headers.class,
    MultiValuedTreeMap.class,
    AwsProxySecurityContext.class
})
@SerdeImport(AlbContext.class)
@SerdeImport(ApiGatewayAuthorizerContext.class)
@SerdeImport(ApiGatewayRequestIdentity.class)
@SerdeImport(AwsProxyRequest.class)
@SerdeImport(AwsProxyRequestContext.class)
@SerdeImport(AwsProxyResponse.class)
@SerdeImport(CognitoAuthorizerClaims.class)
@SerdeImport(ContainerConfig.class)
@SerdeImport(ErrorModel.class)
@SerdeImport(Headers.class)
@SerdeImport(MultiValuedTreeMap.class)
@SerdeImport(AwsProxySecurityContext.class)
@SerdeImport(SingleValueHeaders.class)
```

To `Application.java`

**Comment by sdelamo** [comment]
can you give more context? Is this an error which occurs when deploying a function to a custom runtime as a native executable built with GraalVM? Do you have a sample app and steps to reproduce?

**Comment by driverpt** [comment]
Yes. We have a Micronaut Application to be served from Api Gateway.

**Comment by sdelamo** [comment]
Are these the steps to reproduce it?

- [Create an Application with `amazon-api-gateway`, `aws-lambda`, `graalvm`, `aws-cdk`](https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=JUNIT&features=aws-lambda&features=graalvm&features=amazon-api-gateway&features=aws-cdk&version=3.8.0) 
- Deploy it
- invoke it

**Comment by driverpt** [comment]
@sdelamo , we use `sam` but, it's the same. Sorry, I haven't yet had the time to create an App

**Comment by driverpt** [comment]
Update: This happens also in Micronaut 3.8.1 w/ GraalVM 22.3.0

**Comment by driverpt** [comment]
It works with custom `Serde`:

```
@Singleton
@Slf4j
public class SingleValueHeadersSerde implements Serde<SingleValueHeaders> {
  @Override
  public SingleValueHeaders deserialize(final Decoder decoder, final DecoderContext context, final Argument<? super SingleValueHeaders> type) throws IOException {
    Object object = decoder.decodeArbitrary();
    log.info("Object: {}", object);

    if (object instanceof Map) {
      Map<String, String> map = (Map<String, String>) object;
      SingleValueHeaders result = new SingleValueHeaders();
      result.putAll(map);

      return result;
    }

    throw new IOException("Cannot deserialize into SingleValueHeaders");
  }

  @Override
  public void serialize(final Encoder encoder, final EncoderContext context, final Argument<? extends SingleValueHeaders> type, final SingleValueHeaders value) throws IOException {
    // No Serialization needed
  }
}

```

**Comment by driverpt** [comment]
Logging Output:

```
 "message": "Object: {Content-Length=<redacted>, Content-Type=application/json, Host=<redacted>, User-Agent=HTTPie/3.2.1, X-Amzn-Trace-Id=Root=<redacted>, X-Forwarded-For=<redacted>, X-Forwarded-Port=443, X-Forwarded-Proto=https, accept=application/json, accept-encoding=gzip, deflate}"
```
```
"message": "Object: {proxy=<API Gateway Proxy Path>}"
```

**Comment by driverpt** [comment]
Update:

For some reason, `CountDownLatch` is not being set to 0 on `MicronautLambdaContainerHandler`, causing Lambda Timeout. @sdelamo @graemerocher

**Comment by driverpt** [comment]
@sdelamo @n0tl3ss , the "Starvation" was fixed by downgrading `micronaut-tracing` to 4.4.0. Testing now again with Micronaut 3.8.1

**Comment by driverpt** [comment]
Update: Doesn't work with Micronaut 3.8.1 + Micronaut AWS + Micronaut Tracing 4.4.0. 

Result:
```
Caused by: java.lang.NoClassDefFoundError: io.opentelemetry.instrumentation.api.util.ClassAndMethod
```

**Comment by driverpt** [comment]
Found the Root cause:

```
17:27:45.438 DEBUG [main][i.m.context.DefaultBeanContext] Finding candidate beans for type: RuntimeContext
17:27:45.441 DEBUG [main][i.m.context.DefaultBeanContext] No bean candidates found for type: RuntimeContext
17:27:45.463 DEBUG [main][i.m.context.DefaultBeanContext] Finding candidate beans for type: 
17:27:45.465 DEBUG [main][i.m.context.DefaultBeanContext] No bean candidates found for type: 
17:27:45.770 DEBUG [main][reactor.core.publisher.Operators] Duplicate Subscription has been detected
java.lang.IllegalStateException: Spec. Rule 2.12 - Subscriber.onSubscribe MUST NOT be called more than once (based on object equality)
	at reactor.core.Exceptions.duplicateOnSubscribeException(Exceptions.java:196)
	at reactor.core.publisher.Operators.reportSubscriptionSet(Operators.java:1084)
	at reactor.core.publisher.Operators.setOnce(Operators.java:1189)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:946)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:226)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8663)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher$1.request(Publishers.java:563)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher.subscribe(Publishers.java:553)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
	at io.micronaut.tracing.opentelemetry.instrument.util.OpenTelemetryCorePublisher.doSubscribe(OpenTelemetryCorePublisher.java:55)
	at io.micronaut.tracing.opentelemetry.instrument.util.OpenTelemetryPublisher.subscribe(OpenTelemetryPublisher.java:68)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.filterAndEncodeResponse(MicronautLambdaContainerHandler.java:715)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleStatusError(MicronautLambdaContainerHandler.java:703)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handlePossibleErrorStatus(MicronautLambdaContainerHandler.java:676)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$2(MicronautLambdaContainerHandler.java:332)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:328)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:106)
	at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:205)
	at io.micronaut.function.aws.proxy.MicronautLambdaHandler.handleRequest(MicronautLambdaHandler.java:69)
	at io.micronaut.function.aws.proxy.MicronautLambdaHandler.handleRequest(MicronautLambdaHandler.java:35)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:376)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:146)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:50)

```

**Comment by driverpt** [comment]
Traced this down to `io.opentelemetry.instrumentation.api.instrumenter.http.HttpCommonAttributesExtractor#responseContentLength` which is Null and the `firstHeaderValue` doesn't have Null protection

```
  @Nullable
  static String firstHeaderValue(List<String> values) {
    return values.isEmpty() ? null : values.get(0);
  }
```

Throws NPE here

**Comment by driverpt** [comment]
Did anyone managed to find out the Root Cause?

**Comment by n0tl3ss** [comment]
@driverpt Have you tried this: https://github.com/micronaut-projects/micronaut-aws/pull/1578. It might still require your `SingleValueHeadersSerde` but it would be nice if you could test it first without it :).

Thanks

**Comment by driverpt** [comment]
Hey @n0tl3ss , sorry, haven't had much time lately, I'm swamped with deadlines.

I saw your PR. You changed core stuff in AWS. Should I checkout your branch and build it?

**Comment by n0tl3ss** [comment]
Yes :) I probably can test it myself, but I think because you already have example that doesn't work it would be easier that you verify that change.

**Comment by driverpt** [comment]
I will test it. This weekend most likely. 

In the meanwhile I've created my own [Simulator](https://github.com/driverpt/aws-lambda-runtime-simulator) that allows me to debug locally the code (also available via docker). There's no need to wrap the jar inside the docker container, just a simple web app that simulates aws lambda api

**Comment by driverpt** [comment]
Finally had the time to test it!

Same issue:

Using:
```
    implementation("io.micronaut.aws:micronaut-function-aws-api-proxy:3.12.1-SNAPSHOT")
    implementation("io.micronaut.aws:micronaut-function-aws-custom-runtime:3.12.1-SNAPSHOT")
    implementation("io.micronaut.aws:micronaut-aws-sdk-v2:3.12.1-SNAPSHOT")
    implementation("io.micronaut.tracing:micronaut-tracing-opentelemetry-http:4.5.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("io.opentelemetry:opentelemetry-extension-aws")
    implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2")
    implementation("io.opentelemetry.contrib:opentelemetry-aws-xray")
```

```
java.lang.IllegalStateException: Spec. Rule 2.12 - Subscriber.onSubscribe MUST NOT be called more than once (based on object equality)
	at reactor.core.Exceptions.duplicateOnSubscribeException(Exceptions.java:196)
	at reactor.core.publisher.Operators.reportSubscriptionSet(Operators.java:1084)
	at reactor.core.publisher.Operators.setOnce(Operators.java:1189)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:946)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:226)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8663)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher$1.request(Publishers.java:563)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher.subscribe(Publishers.java:553)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
	at io.micronaut.tracing.opentelemetry.instrument.util.OpenTelemetryCorePublisher.doSubscribe(OpenTelemetryCorePublisher.java:55)
	at io.micronaut.tracing.opentelemetry.instrument.util.OpenTelemetryPublisher.subscribe(OpenTelemetryPublisher.java:68)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8660)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.filterAndEncodeResponse(MicronautLambdaContainerHandler.java:715)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleStatusError(MicronautLambdaContainerHandler.java:703)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handlePossibleErrorStatus(MicronautLambdaContainerHandler.java:676)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$2(MicronautLambdaContainerHandler.java:332)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:328)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:106)

```

**Comment by driverpt** [comment]
Why not switch from `subscribe()` to Block? A `CountDownLatch` is being used so in the end it's being blocked anyway

**Comment by sdelamo** [comment]
Micronaut AWS 3.10.7 should solve this issue. I have been able to deploy a native executable with custom headers.

**Comment by sdelamo** [comment]
@driverpt reopen if you still are not able to deploy a native image to a custom runtime with 3.10.7.

**Comment by driverpt** [comment]
In 3.8.3 we still get Lambda Timeout and Freeze. Testing with 3.7.x

**Comment by driverpt** [comment]
With 3.7.6

![image](https://user-images.githubusercontent.com/1164534/216653751-51553b61-a548-48d1-9543-594b4a8fd010.png)

**Comment by n0tl3ss** [comment]
Hi @driverpt, can you share full stack trace, and did you deploy it as jar or native image? :)

**Comment by driverpt** [comment]
Native Image. Will test with JAR next week

**Comment by n0tl3ss** [comment]
I think it might be that we are missing some configurations for native-image, as you probably know OpenTelemetry often has some refactoring and new features in every release. :)

**Comment by driverpt** [comment]
Also. There's no stack trace, lambda initializes and just dies. According to the logs, Controller code is executed, so this most likely happens on response, and I suspect has something to do with CountDownLatch
